# coding=utf-8
import json

exercises = []

def add(lang, translation, target, words):
    exercises.append(f'    SentenceExercise("{target}", "{translation}", listOf({", ".join([f"\"{w}\"" for w in words])}), "{lang}")')

# --- EN (English) ---
add("en", "Eu gosto de comer maçãs", "I like to eat apples", ["I", "like", "to", "eat", "apples"])
add("en", "Onde fica a casa de banho?", "Where is the bathroom?", ["Where", "is", "the", "bathroom?"])
add("en", "O meu nome é João", "My name is John", ["My", "name", "is", "John"])
add("en", "Quanto custa isto?", "How much does this cost?", ["How", "much", "does", "this", "cost?"])
add("en", "Eu gostaria de um café", "I would like a coffee", ["I", "would", "like", "a", "coffee"])
add("en", "Onde fica a estação de comboios?", "Where is the train station?", ["Where", "is", "the", "train", "station?"])
add("en", "Eu não entendo", "I don't understand", ["I", "don't", "understand"])
add("en", "Que horas são?", "What time is it?", ["What", "time", "is", "it?"])
add("en", "A conta, por favor", "The check, please", ["The", "check,", "please"])
add("en", "Tenho uma reserva", "I have a reservation", ["I", "have", "a", "reservation"])
add("en", "Preciso de ajuda", "I need help", ["I", "need", "help"])
add("en", "Prazer em conhecer-te", "Nice to meet you", ["Nice", "to", "meet", "you"])
add("en", "Como estás?", "How are you?", ["How", "are", "you?"])
add("en", "Estou muito bem", "I am very well", ["I", "am", "very", "well"])
add("en", "Hoje o tempo está bom", "The weather is good today", ["The", "weather", "is", "good", "today"])

# --- ES (Spanish) ---
add("es", "Eu gosto de comer maçãs", "Me gusta comer manzanas", ["Me", "gusta", "comer", "manzanas"])
add("es", "Onde fica a casa de banho?", "¿Dónde está el baño?", ["¿Dónde", "está", "el", "baño?"])
add("es", "O meu nome é João", "Me llamo Juan", ["Me", "llamo", "Juan"])
add("es", "Quanto custa isto?", "¿Cuánto cuesta esto?", ["¿Cuánto", "cuesta", "esto?"])
add("es", "Eu gostaria de um café", "Quisiera un café", ["Quisiera", "un", "café"])
add("es", "Onde fica a estação de comboios?", "¿Dónde está la estación de tren?", ["¿Dónde", "está", "la", "estación", "de", "tren?"])
add("es", "Eu não entendo", "No entiendo", ["No", "entiendo"])
add("es", "Que horas são?", "¿Qué hora es?", ["¿Qué", "hora", "es?"])
add("es", "A conta, por favor", "La cuenta, por favor", ["La", "cuenta,", "por", "favor"])
add("es", "Tenho uma reserva", "Tengo una reserva", ["Tengo", "una", "reserva"])
add("es", "Preciso de ajuda", "Necesito ayuda", ["Necesito", "ayuda"])
add("es", "Prazer em conhecer-te", "Mucho gusto", ["Mucho", "gusto"])
add("es", "Como estás?", "¿Cómo estás?", ["¿Cómo", "estás?"])
add("es", "Estou muito bem", "Estoy muy bien", ["Estoy", "muy", "bien"])
add("es", "Hoje o tempo está bom", "Hoy hace buen tiempo", ["Hoy", "hace", "buen", "tiempo"])

# --- FR (French) ---
add("fr", "Eu gosto de comer maçãs", "J'aime manger des pommes", ["J'aime", "manger", "des", "pommes"])
add("fr", "Onde fica a casa de banho?", "Où sont les toilettes?", ["Où", "sont", "les", "toilettes?"])
add("fr", "O meu nome é João", "Je m'appelle Jean", ["Je", "m'appelle", "Jean"])
add("fr", "Quanto custa isto?", "Combien ça coûte?", ["Combien", "ça", "coûte?"])
add("fr", "Eu gostaria de um café", "Je voudrais un café", ["Je", "voudrais", "un", "café"])
add("fr", "Onde fica a estação de comboios?", "Où est la gare?", ["Où", "est", "la", "gare?"])
add("fr", "Eu não entendo", "Je ne comprends pas", ["Je", "ne", "comprends", "pas"])
add("fr", "Que horas são?", "Quelle heure est-il?", ["Quelle", "heure", "est-il?"])
add("fr", "A conta, por favor", "L'addition, s'il vous plaît", ["L'addition,", "s'il", "vous", "plaît"])
add("fr", "Tenho uma reserva", "J'ai une réservation", ["J'ai", "une", "réservation"])
add("fr", "Preciso de ajuda", "J'ai besoin d'aide", ["J'ai", "besoin", "d'aide"])
add("fr", "Prazer em conhecer-te", "Enchanté", ["Enchanté"])
add("fr", "Como estás?", "Comment allez-vous?", ["Comment", "allez-vous?"])
add("fr", "Estou muito bem", "Je vais très bien", ["Je", "vais", "très", "bien"])
add("fr", "Hoje o tempo está bom", "Il fait beau aujourd'hui", ["Il", "fait", "beau", "aujourd'hui"])

# --- DE (German) ---
add("de", "Eu gosto de comer maçãs", "Ich esse gerne Äpfel", ["Ich", "esse", "gerne", "Äpfel"])
add("de", "Onde fica a casa de banho?", "Wo ist die Toilette?", ["Wo", "ist", "die", "Toilette?"])
add("de", "O meu nome é João", "Mein Name ist Johannes", ["Mein", "Name", "ist", "Johannes"])
add("de", "Quanto custa isto?", "Wie viel kostet das?", ["Wie", "viel", "kostet", "das?"])
add("de", "Eu gostaria de um café", "Ich hätte gerne einen Kaffee", ["Ich", "hätte", "gerne", "einen", "Kaffee"])
add("de", "Onde fica a estação de comboios?", "Wo ist der Bahnhof?", ["Wo", "ist", "der", "Bahnhof?"])
add("de", "Eu não entendo", "Ich verstehe nicht", ["Ich", "verstehe", "nicht"])
add("de", "Que horas são?", "Wie spät ist es?", ["Wie", "spät", "ist", "es?"])
add("de", "A conta, por favor", "Die Rechnung, bitte", ["Die", "Rechnung,", "bitte"])
add("de", "Tenho uma reserva", "Ich habe eine Reservierung", ["Ich", "habe", "eine", "Reservierung"])
add("de", "Preciso de ajuda", "Ich brauche Hilfe", ["Ich", "brauche", "Hilfe"])
add("de", "Prazer em conhecer-te", "Schön dich kennenzulernen", ["Schön", "dich", "kennenzulernen"])
add("de", "Como estás?", "Wie geht es dir?", ["Wie", "geht", "es", "dir?"])
add("de", "Estou muito bem", "Mir geht es sehr gut", ["Mir", "geht", "es", "sehr", "gut"])
add("de", "Hoje o tempo está bom", "Das Wetter ist heute gut", ["Das", "Wetter", "ist", "heute", "gut"])

# --- IT (Italian) ---
add("it", "Eu gosto de comer maçãs", "Mi piace mangiare le mele", ["Mi", "piace", "mangiare", "le", "mele"])
add("it", "Onde fica a casa de banho?", "Dov'è il bagno?", ["Dov'è", "il", "bagno?"])
add("it", "O meu nome é João", "Mi chiamo Giovanni", ["Mi", "chiamo", "Giovanni"])
add("it", "Quanto custa isto?", "Quanto costa questo?", ["Quanto", "costa", "questo?"])
add("it", "Eu gostaria de um café", "Vorrei un caffè", ["Vorrei", "un", "caffè"])
add("it", "Onde fica a estação de comboios?", "Dov'è la stazione dei treni?", ["Dov'è", "la", "stazione", "dei", "treni?"])
add("it", "Eu não entendo", "Non capisco", ["Non", "capisco"])
add("it", "Que horas são?", "Che ore sono?", ["Che", "ore", "sono?"])
add("it", "A conta, por favor", "Il conto, per favore", ["Il", "conto,", "per", "favore"])
add("it", "Tenho uma reserva", "Ho una prenotazione", ["Ho", "una", "prenotazione"])
add("it", "Preciso de ajuda", "Ho bisogno di aiuto", ["Ho", "bisogno", "di", "aiuto"])
add("it", "Prazer em conhecer-te", "Piacere di conoscerti", ["Piacere", "di", "conoscerti"])
add("it", "Como estás?", "Come stai?", ["Come", "stai?"])
add("it", "Estou muito bem", "Sto molto bene", ["Sto", "molto", "bene"])
add("it", "Hoje o tempo está bom", "Oggi fa bel tempo", ["Oggi", "fa", "bel", "tempo"])

# --- NL (Dutch) ---
add("nl", "Eu gosto de comer maçãs", "Ik eet graag appels", ["Ik", "eet", "graag", "appels"])
add("nl", "Onde fica a casa de banho?", "Waar is het toilet?", ["Waar", "is", "het", "toilet?"])
add("nl", "O meu nome é João", "Mijn naam is Jan", ["Mijn", "naam", "is", "Jan"])
add("nl", "Quanto custa isto?", "Hoeveel kost dit?", ["Hoeveel", "kost", "dit?"])
add("nl", "Eu gostaria de um café", "Ik wil graag een koffie", ["Ik", "wil", "graag", "een", "koffie"])
add("nl", "Onde fica a estação de comboios?", "Waar is het treinstation?", ["Waar", "is", "het", "treinstation?"])
add("nl", "Eu não entendo", "Ik begrijp het niet", ["Ik", "begrijp", "het", "niet"])
add("nl", "Que horas são?", "Hoe laat is het?", ["Hoe", "laat", "is", "het?"])
add("nl", "A conta, por favor", "De rekening, alstublieft", ["De", "rekening,", "alstublieft"])
add("nl", "Tenho uma reserva", "Ik heb een reservering", ["Ik", "heb", "een", "reservering"])
add("nl", "Preciso de ajuda", "Ik heb hulp nodig", ["Ik", "heb", "hulp", "nodig"])
add("nl", "Prazer em conhecer-te", "Aangenaam kennis te maken", ["Aangenaam", "kennis", "te", "maken"])
add("nl", "Como estás?", "Hoe gaat het?", ["Hoe", "gaat", "het?"])
add("nl", "Estou muito bem", "Het gaat heel goed", ["Het", "gaat", "heel", "goed"])
add("nl", "Hoje o tempo está bom", "Het is mooi weer vandaag", ["Het", "is", "mooi", "weer", "vandaag"])

# --- KO (Korean) ---
add("ko", "Eu gosto de comer maçãs", "저는 사과를 먹는 것을 좋아합니다", ["저는", "사과를", "먹는", "것을", "좋아합니다"])
add("ko", "Onde fica a casa de banho?", "화장실이 어디 있나요?", ["화장실이", "어디", "있나요?"])
add("ko", "O meu nome é João", "제 이름은 존입니다", ["제", "이름은", "존입니다"])
add("ko", "Quanto custa isto?", "이거 얼마예요?", ["이거", "얼마예요?"])
add("ko", "Eu gostaria de um café", "커피 한 잔 부탁합니다", ["커피", "한", "잔", "부탁합니다"])
add("ko", "Onde fica a estação de comboios?", "기차역이 어디인가요?", ["기차역이", "어디인가요?"])
add("ko", "Eu não entendo", "이해가 안 가요", ["이해가", "안", "가요"])
add("ko", "Que horas são?", "지금 몇 시예요?", ["지금", "몇", "시예요?"])
add("ko", "A conta, por favor", "계산서 부탁합니다", ["계산서", "부탁합니다"])
add("ko", "Tenho uma reserva", "예약했습니다", ["예약했습니다"])
add("ko", "Preciso de ajuda", "도움이 필요해요", ["도움이", "필요해요"])
add("ko", "Prazer em conhecer-te", "만나서 반갑습니다", ["만나서", "반갑습니다"])
add("ko", "Como estás?", "어떻게 지내세요?", ["어떻게", "지내세요?"])
add("ko", "Estou muito bem", "저는 아주 잘 지냅니다", ["저는", "아주", "잘", "지냅니다"])
add("ko", "Hoje o tempo está bom", "오늘 날씨가 좋네요", ["오늘", "날씨가", "좋네요"])

# --- JA (Japanese) ---
add("ja", "Eu gosto de comer maçãs", "りんごを食べるのが好きです", ["りんごを", "食べるのが", "好きです"])
add("ja", "Onde fica a casa de banho?", "トイレはどこですか？", ["トイレは", "どこですか？"])
add("ja", "O meu nome é João", "私の名前はジョンです", ["私の名前は", "ジョンです"])
add("ja", "Quanto custa isto?", "これはいくらですか？", ["これは", "いくらですか？"])
add("ja", "Eu gostaria de um café", "コーヒーをお願いします", ["コーヒーを", "お願いします"])
add("ja", "Onde fica a estação de comboios?", "駅はどこですか？", ["駅は", "どこですか？"])
add("ja", "Eu não entendo", "わかりません", ["わかりません"])
add("ja", "Que horas são?", "今何時ですか？", ["今", "何時ですか？"])
add("ja", "A conta, por favor", "お会計をお願いします", ["お会計を", "お願いします"])
add("ja", "Tenho uma reserva", "予約しています", ["予約しています"])
add("ja", "Preciso de ajuda", "助けが必要です", ["助けが", "必要です"])
add("ja", "Prazer em conhecer-te", "はじめまして", ["はじめまして"])
add("ja", "Como estás?", "お元気ですか？", ["お元気ですか？"])
add("ja", "Estou muito bem", "とても元気です", ["とても", "元気です"])
add("ja", "Hoje o tempo está bom", "今日は天気がいいですね", ["今日は", "天気が", "いいですね"])

# --- ZH (Chinese) ---
add("zh", "Eu gosto de comer maçãs", "我喜欢吃苹果", ["我", "喜欢", "吃", "苹果"])
add("zh", "Onde fica a casa de banho?", "洗手间在哪里？", ["洗手间", "在", "哪里？"])
add("zh", "O meu nome é João", "我叫约翰", ["我", "叫", "约翰"])
add("zh", "Quanto custa isto?", "这个多少钱？", ["这个", "多少钱？"])
add("zh", "Eu gostaria de um café", "我想要一杯咖啡", ["我", "想要", "一杯咖啡"])
add("zh", "Onde fica a estação de comboios?", "火车站在哪里？", ["火车站", "在", "哪里？"])
add("zh", "Eu não entendo", "我不明白", ["我", "不", "明白"])
add("zh", "Que horas são?", "现在几点？", ["现在", "几点？"])
add("zh", "A conta, por favor", "买单，谢谢", ["买单，", "谢谢"])
add("zh", "Tenho uma reserva", "我有一个预订", ["我", "有一个预订"])
add("zh", "Preciso de ajuda", "我需要帮助", ["我", "需要帮助"])
add("zh", "Prazer em conhecer-te", "很高兴认识你", ["很", "高兴", "认识", "你"])
add("zh", "Como estás?", "你好吗？", ["你", "好吗？"])
add("zh", "Estou muito bem", "我很好", ["我", "很好"])
add("zh", "Hoje o tempo está bom", "今天天气很好", ["今天", "天气", "很好"])

# --- VI (Vietnamese) ---
add("vi", "Eu gosto de comer maçãs", "Tôi thích ăn táo", ["Tôi", "thích", "ăn", "táo"])
add("vi", "Onde fica a casa de banho?", "Phòng tắm ở đâu?", ["Phòng", "tắm", "ở", "đâu?"])
add("vi", "O meu nome é João", "Tên tôi là John", ["Tên", "tôi", "là", "John"])
add("vi", "Quanto custa isto?", "Cái này giá bao nhiêu?", ["Cái", "này", "giá", "bao", "nhiêu?"])
add("vi", "Eu gostaria de um café", "Tôi muốn một ly cà phê", ["Tôi", "muốn", "một", "ly", "cà", "phê"])
add("vi", "Onde fica a estação de comboios?", "Ga tàu ở đâu?", ["Ga", "tàu", "ở", "đâu?"])
add("vi", "Eu não entendo", "Tôi không hiểu", ["Tôi", "không", "hiểu"])
add("vi", "Que horas são?", "Bây giờ là mấy giờ?", ["Bây", "giờ", "là", "mấy", "giờ?"])
add("vi", "A conta, por favor", "Tính tiền, xin vui lòng", ["Tính", "tiền,", "xin", "vui", "lòng"])
add("vi", "Tenho uma reserva", "Tôi có một đặt chỗ", ["Tôi", "có", "một", "đặt", "chỗ"])
add("vi", "Preciso de ajuda", "Tôi cần giúp đỡ", ["Tôi", "cần", "giúp", "đỡ"])
add("vi", "Prazer em conhecer-te", "Rất vui được gặp bạn", ["Rất", "vui", "được", "gặp", "bạn"])
add("vi", "Como estás?", "Bạn khỏe không?", ["Bạn", "khỏe", "không?"])
add("vi", "Estou muito bem", "Tôi rất khỏe", ["Tôi", "rất", "khỏe"])
add("vi", "Hoje o tempo está bom", "Hôm nay thời tiết đẹp", ["Hôm", "nay", "thời", "tiết", "đẹp"])

# --- HI (Hindi) ---
add("hi", "Eu gosto de comer maçãs", "मुझे सेब खाना पसंद है", ["मुझे", "सेब", "खाना", "पसंद", "है"])
add("hi", "Onde fica a casa de banho?", "बाथरूम कहाँ है?", ["बाथरूम", "कहाँ", "है?"])
add("hi", "O meu nome é João", "मेरा नाम जॉन है", ["मेरा", "नाम", "जॉन", "है"])
add("hi", "Quanto custa isto?", "इसकी कीमत क्या है?", ["इसकी", "कीमत", "क्या", "है?"])
add("hi", "Eu gostaria de um café", "मुझे एक कॉफी चाहिए", ["मुझे", "एक", "कॉफी", "चाहिए"])
add("hi", "Onde fica a estação de comboios?", "ट्रेन स्टेशन कहाँ है?", ["ट्रेन", "स्टेशन", "कहाँ", "है?"])
add("hi", "Eu não entendo", "मुझे समझ नहीं आ रहा है", ["मुझे", "समझ", "नहीं", "आ", "रहा", "है"])
add("hi", "Que horas são?", "समय क्या हुआ है?", ["समय", "क्या", "हुआ", "है?"])
add("hi", "A conta, por favor", "बिल, कृपया", ["बिल,", "कृपया"])
add("hi", "Tenho uma reserva", "मेरे पास आरक्षण है", ["मेरे", "पास", "आरक्षण", "है"])
add("hi", "Preciso de ajuda", "मुझे मदद चाहिए", ["मुझे", "मदद", "चाहिए"])
add("hi", "Prazer em conhecer-te", "आपसे मिलकर अच्छा लगा", ["आपसे", "मिलकर", "अच्छा", "लगा"])
add("hi", "Como estás?", "आप कैसे हैं?", ["आप", "कैसे", "हैं?"])
add("hi", "Estou muito bem", "मैं बहुत अच्छा हूँ", ["मैं", "बहुत", "अच्छा", "हूँ"])
add("hi", "Hoje o tempo está bom", "आज मौसम अच्छा है", ["आज", "मौसम", "अच्छा", "है"])

# --- AR (Arabic) ---
add("ar", "Eu gosto de comer maçãs", "أحب أكل التفاح", ["أحب", "أكل", "التفاح"])
add("ar", "Onde fica a casa de banho?", "أين الحمام؟", ["أين", "الحمام؟"])
add("ar", "O meu nome é João", "اسمي جون", ["اسمي", "جون"])
add("ar", "Quanto custa isto?", "كم يكلف هذا؟", ["كم", "يكلف", "هذا؟"])
add("ar", "Eu gostaria de um café", "أريد قهوة", ["أريد", "قهوة"])
add("ar", "Onde fica a estação de comboios?", "أين محطة القطار؟", ["أين", "محطة", "القطار؟"])
add("ar", "Eu não entendo", "لا أفهم", ["لا", "أفهم"])
add("ar", "Que horas são?", "كم الساعة؟", ["كم", "الساعة؟"])
add("ar", "A conta, por favor", "الفاتورة من فضلك", ["الفاتورة", "من", "فضلك"])
add("ar", "Tenho uma reserva", "لدي حجز", ["لدي", "حجز"])
add("ar", "Preciso de ajuda", "أحتاج إلى المساعدة", ["أحتاج", "إلى", "المساعدة"])
add("ar", "Prazer em conhecer-te", "سعيد بلقائك", ["سعيد", "بلقائك"])
add("ar", "Como estás?", "كيف حالك؟", ["كيف", "حالك؟"])
add("ar", "Estou muito bem", "أنا بخير جدا", ["أنا", "بخير", "جدا"])
add("ar", "Hoje o tempo está bom", "الطقس جيد اليوم", ["الطقس", "جيد", "اليوم"])

# --- TH (Thai) ---
add("th", "Eu gosto de comer maçãs", "ฉันชอบกินแอปเปิ้ล", ["ฉัน", "ชอบ", "กิน", "แอปเปิ้ล"])
add("th", "Onde fica a casa de banho?", "ห้องน้ำอยู่ที่ไหน?", ["ห้องน้ำ", "อยู่", "ที่ไหน?"])
add("th", "O meu nome é João", "ฉันชื่อจอห์น", ["ฉัน", "ชื่อ", "จอห์น"])
add("th", "Quanto custa isto?", "อันนี้ราคาเท่าไหร่?", ["อันนี้", "ราคา", "เท่าไหร่?"])
add("th", "Eu gostaria de um café", "ฉันขอรับกาแฟ", ["ฉัน", "ขอรับ", "กาแฟ"])
add("th", "Onde fica a estação de comboios?", "สถานีรถไฟอยู่ที่ไหน?", ["สถานีรถไฟ", "อยู่", "ที่ไหน?"])
add("th", "Eu não entendo", "ฉันไม่เข้าใจ", ["ฉัน", "ไม่", "เข้าใจ"])
add("th", "Que horas são?", "ตอนนี้กี่โมงแล้ว?", ["ตอนนี้", "กี่โมง", "แล้ว?"])
add("th", "A conta, por favor", "เช็คบิลด้วยครับ", ["เช็คบิล", "ด้วยครับ"])
add("th", "Tenho uma reserva", "ฉันมีการจองไว้", ["ฉันมี", "การจอง", "ไว้"])
add("th", "Preciso de ajuda", "ฉันต้องการความช่วยเหลือ", ["ฉันต้องการ", "ความช่วยเหลือ"])
add("th", "Prazer em conhecer-te", "ยินดีที่ได้รู้จัก", ["ยินดี", "ที่ได้", "รู้จัก"])
add("th", "Como estás?", "คุณเป็นอย่างไรบ้าง?", ["คุณ", "เป็น", "อย่างไรบ้าง?"])
add("th", "Estou muito bem", "ฉันสบายดีมาก", ["ฉัน", "สบายดี", "มาก"])
add("th", "Hoje o tempo está bom", "วันนี้อากาศดี", ["วันนี้", "อากาศดี"])


with open("app/src/main/java/com/linguaflow/app/domain/model/SentenceExercisesData.kt", "w", encoding="utf-8") as f:
    f.write("package com.linguaflow.app.domain.model\n\n")
    f.write("data class SentenceExercise(\n")
    f.write("    val targetSentence: String,\n")
    f.write("    val translation: String,\n")
    f.write("    val words: List<String>,\n")
    f.write("    val languageCode: String\n")
    f.write(")\n\n")
    f.write("val globalSentenceExercises = listOf(\n")
    f.write(",\n".join(exercises))
    f.write("\n)\n")
