package com.linguaflow.app.domain.model

data class SentenceExercise(
    val targetSentence: String,
    val translation: String,
    val words: List<String>,
    val languageCode: String
)

val globalSentenceExercises = listOf(
    SentenceExercise("I like to eat apples", "Eu gosto de comer maçãs", listOf("I", "like", "to", "eat", "apples"), "en"),
    SentenceExercise("Where is the bathroom?", "Onde fica a casa de banho?", listOf("Where", "is", "the", "bathroom?"), "en"),
    SentenceExercise("My name is John", "O meu nome é João", listOf("My", "name", "is", "John"), "en"),
    SentenceExercise("How much does this cost?", "Quanto custa isto?", listOf("How", "much", "does", "this", "cost?"), "en"),
    SentenceExercise("I would like a coffee", "Eu gostaria de um café", listOf("I", "would", "like", "a", "coffee"), "en"),
    SentenceExercise("Where is the train station?", "Onde fica a estação de comboios?", listOf("Where", "is", "the", "train", "station?"), "en"),
    SentenceExercise("I don't understand", "Eu não entendo", listOf("I", "don't", "understand"), "en"),
    SentenceExercise("What time is it?", "Que horas são?", listOf("What", "time", "is", "it?"), "en"),
    SentenceExercise("The check, please", "A conta, por favor", listOf("The", "check,", "please"), "en"),
    SentenceExercise("I have a reservation", "Tenho uma reserva", listOf("I", "have", "a", "reservation"), "en"),
    SentenceExercise("I need help", "Preciso de ajuda", listOf("I", "need", "help"), "en"),
    SentenceExercise("Nice to meet you", "Prazer em conhecer-te", listOf("Nice", "to", "meet", "you"), "en"),
    SentenceExercise("How are you?", "Como estás?", listOf("How", "are", "you?"), "en"),
    SentenceExercise("I am very well", "Estou muito bem", listOf("I", "am", "very", "well"), "en"),
    SentenceExercise("The weather is good today", "Hoje o tempo está bom", listOf("The", "weather", "is", "good", "today"), "en"),
    SentenceExercise("Me gusta comer manzanas", "Eu gosto de comer maçãs", listOf("Me", "gusta", "comer", "manzanas"), "es"),
    SentenceExercise("¿Dónde está el baño?", "Onde fica a casa de banho?", listOf("¿Dónde", "está", "el", "baño?"), "es"),
    SentenceExercise("Me llamo Juan", "O meu nome é João", listOf("Me", "llamo", "Juan"), "es"),
    SentenceExercise("¿Cuánto cuesta esto?", "Quanto custa isto?", listOf("¿Cuánto", "cuesta", "esto?"), "es"),
    SentenceExercise("Quisiera un café", "Eu gostaria de um café", listOf("Quisiera", "un", "café"), "es"),
    SentenceExercise("¿Dónde está la estación de tren?", "Onde fica a estação de comboios?", listOf("¿Dónde", "está", "la", "estación", "de", "tren?"), "es"),
    SentenceExercise("No entiendo", "Eu não entendo", listOf("No", "entiendo"), "es"),
    SentenceExercise("¿Qué hora es?", "Que horas são?", listOf("¿Qué", "hora", "es?"), "es"),
    SentenceExercise("La cuenta, por favor", "A conta, por favor", listOf("La", "cuenta,", "por", "favor"), "es"),
    SentenceExercise("Tengo una reserva", "Tenho uma reserva", listOf("Tengo", "una", "reserva"), "es"),
    SentenceExercise("Necesito ayuda", "Preciso de ajuda", listOf("Necesito", "ayuda"), "es"),
    SentenceExercise("Mucho gusto", "Prazer em conhecer-te", listOf("Mucho", "gusto"), "es"),
    SentenceExercise("¿Cómo estás?", "Como estás?", listOf("¿Cómo", "estás?"), "es"),
    SentenceExercise("Estoy muy bien", "Estou muito bem", listOf("Estoy", "muy", "bien"), "es"),
    SentenceExercise("Hoy hace buen tiempo", "Hoje o tempo está bom", listOf("Hoy", "hace", "buen", "tiempo"), "es"),
    SentenceExercise("J'aime manger des pommes", "Eu gosto de comer maçãs", listOf("J'aime", "manger", "des", "pommes"), "fr"),
    SentenceExercise("Où sont les toilettes?", "Onde fica a casa de banho?", listOf("Où", "sont", "les", "toilettes?"), "fr"),
    SentenceExercise("Je m'appelle Jean", "O meu nome é João", listOf("Je", "m'appelle", "Jean"), "fr"),
    SentenceExercise("Combien ça coûte?", "Quanto custa isto?", listOf("Combien", "ça", "coûte?"), "fr"),
    SentenceExercise("Je voudrais un café", "Eu gostaria de um café", listOf("Je", "voudrais", "un", "café"), "fr"),
    SentenceExercise("Où est la gare?", "Onde fica a estação de comboios?", listOf("Où", "est", "la", "gare?"), "fr"),
    SentenceExercise("Je ne comprends pas", "Eu não entendo", listOf("Je", "ne", "comprends", "pas"), "fr"),
    SentenceExercise("Quelle heure est-il?", "Que horas são?", listOf("Quelle", "heure", "est-il?"), "fr"),
    SentenceExercise("L'addition, s'il vous plaît", "A conta, por favor", listOf("L'addition,", "s'il", "vous", "plaît"), "fr"),
    SentenceExercise("J'ai une réservation", "Tenho uma reserva", listOf("J'ai", "une", "réservation"), "fr"),
    SentenceExercise("J'ai besoin d'aide", "Preciso de ajuda", listOf("J'ai", "besoin", "d'aide"), "fr"),
    SentenceExercise("Enchanté", "Prazer em conhecer-te", listOf("Enchanté"), "fr"),
    SentenceExercise("Comment allez-vous?", "Como estás?", listOf("Comment", "allez-vous?"), "fr"),
    SentenceExercise("Je vais très bien", "Estou muito bem", listOf("Je", "vais", "très", "bien"), "fr"),
    SentenceExercise("Il fait beau aujourd'hui", "Hoje o tempo está bom", listOf("Il", "fait", "beau", "aujourd'hui"), "fr"),
    SentenceExercise("Ich esse gerne Äpfel", "Eu gosto de comer maçãs", listOf("Ich", "esse", "gerne", "Äpfel"), "de"),
    SentenceExercise("Wo ist die Toilette?", "Onde fica a casa de banho?", listOf("Wo", "ist", "die", "Toilette?"), "de"),
    SentenceExercise("Mein Name ist Johannes", "O meu nome é João", listOf("Mein", "Name", "ist", "Johannes"), "de"),
    SentenceExercise("Wie viel kostet das?", "Quanto custa isto?", listOf("Wie", "viel", "kostet", "das?"), "de"),
    SentenceExercise("Ich hätte gerne einen Kaffee", "Eu gostaria de um café", listOf("Ich", "hätte", "gerne", "einen", "Kaffee"), "de"),
    SentenceExercise("Wo ist der Bahnhof?", "Onde fica a estação de comboios?", listOf("Wo", "ist", "der", "Bahnhof?"), "de"),
    SentenceExercise("Ich verstehe nicht", "Eu não entendo", listOf("Ich", "verstehe", "nicht"), "de"),
    SentenceExercise("Wie spät ist es?", "Que horas são?", listOf("Wie", "spät", "ist", "es?"), "de"),
    SentenceExercise("Die Rechnung, bitte", "A conta, por favor", listOf("Die", "Rechnung,", "bitte"), "de"),
    SentenceExercise("Ich habe eine Reservierung", "Tenho uma reserva", listOf("Ich", "habe", "eine", "Reservierung"), "de"),
    SentenceExercise("Ich brauche Hilfe", "Preciso de ajuda", listOf("Ich", "brauche", "Hilfe"), "de"),
    SentenceExercise("Schön dich kennenzulernen", "Prazer em conhecer-te", listOf("Schön", "dich", "kennenzulernen"), "de"),
    SentenceExercise("Wie geht es dir?", "Como estás?", listOf("Wie", "geht", "es", "dir?"), "de"),
    SentenceExercise("Mir geht es sehr gut", "Estou muito bem", listOf("Mir", "geht", "es", "sehr", "gut"), "de"),
    SentenceExercise("Das Wetter ist heute gut", "Hoje o tempo está bom", listOf("Das", "Wetter", "ist", "heute", "gut"), "de"),
    SentenceExercise("Mi piace mangiare le mele", "Eu gosto de comer maçãs", listOf("Mi", "piace", "mangiare", "le", "mele"), "it"),
    SentenceExercise("Dov'è il bagno?", "Onde fica a casa de banho?", listOf("Dov'è", "il", "bagno?"), "it"),
    SentenceExercise("Mi chiamo Giovanni", "O meu nome é João", listOf("Mi", "chiamo", "Giovanni"), "it"),
    SentenceExercise("Quanto costa questo?", "Quanto custa isto?", listOf("Quanto", "costa", "questo?"), "it"),
    SentenceExercise("Vorrei un caffè", "Eu gostaria de um café", listOf("Vorrei", "un", "caffè"), "it"),
    SentenceExercise("Dov'è la stazione dei treni?", "Onde fica a estação de comboios?", listOf("Dov'è", "la", "stazione", "dei", "treni?"), "it"),
    SentenceExercise("Non capisco", "Eu não entendo", listOf("Non", "capisco"), "it"),
    SentenceExercise("Che ore sono?", "Que horas são?", listOf("Che", "ore", "sono?"), "it"),
    SentenceExercise("Il conto, per favore", "A conta, por favor", listOf("Il", "conto,", "per", "favore"), "it"),
    SentenceExercise("Ho una prenotazione", "Tenho uma reserva", listOf("Ho", "una", "prenotazione"), "it"),
    SentenceExercise("Ho bisogno di aiuto", "Preciso de ajuda", listOf("Ho", "bisogno", "di", "aiuto"), "it"),
    SentenceExercise("Piacere di conoscerti", "Prazer em conhecer-te", listOf("Piacere", "di", "conoscerti"), "it"),
    SentenceExercise("Come stai?", "Como estás?", listOf("Come", "stai?"), "it"),
    SentenceExercise("Sto molto bene", "Estou muito bem", listOf("Sto", "molto", "bene"), "it"),
    SentenceExercise("Oggi fa bel tempo", "Hoje o tempo está bom", listOf("Oggi", "fa", "bel", "tempo"), "it"),
    SentenceExercise("Ik eet graag appels", "Eu gosto de comer maçãs", listOf("Ik", "eet", "graag", "appels"), "nl"),
    SentenceExercise("Waar is het toilet?", "Onde fica a casa de banho?", listOf("Waar", "is", "het", "toilet?"), "nl"),
    SentenceExercise("Mijn naam is Jan", "O meu nome é João", listOf("Mijn", "naam", "is", "Jan"), "nl"),
    SentenceExercise("Hoeveel kost dit?", "Quanto custa isto?", listOf("Hoeveel", "kost", "dit?"), "nl"),
    SentenceExercise("Ik wil graag een koffie", "Eu gostaria de um café", listOf("Ik", "wil", "graag", "een", "koffie"), "nl"),
    SentenceExercise("Waar is het treinstation?", "Onde fica a estação de comboios?", listOf("Waar", "is", "het", "treinstation?"), "nl"),
    SentenceExercise("Ik begrijp het niet", "Eu não entendo", listOf("Ik", "begrijp", "het", "niet"), "nl"),
    SentenceExercise("Hoe laat is het?", "Que horas são?", listOf("Hoe", "laat", "is", "het?"), "nl"),
    SentenceExercise("De rekening, alstublieft", "A conta, por favor", listOf("De", "rekening,", "alstublieft"), "nl"),
    SentenceExercise("Ik heb een reservering", "Tenho uma reserva", listOf("Ik", "heb", "een", "reservering"), "nl"),
    SentenceExercise("Ik heb hulp nodig", "Preciso de ajuda", listOf("Ik", "heb", "hulp", "nodig"), "nl"),
    SentenceExercise("Aangenaam kennis te maken", "Prazer em conhecer-te", listOf("Aangenaam", "kennis", "te", "maken"), "nl"),
    SentenceExercise("Hoe gaat het?", "Como estás?", listOf("Hoe", "gaat", "het?"), "nl"),
    SentenceExercise("Het gaat heel goed", "Estou muito bem", listOf("Het", "gaat", "heel", "goed"), "nl"),
    SentenceExercise("Het is mooi weer vandaag", "Hoje o tempo está bom", listOf("Het", "is", "mooi", "weer", "vandaag"), "nl"),
    SentenceExercise("저는 사과를 먹는 것을 좋아합니다", "Eu gosto de comer maçãs", listOf("저는", "사과를", "먹는", "것을", "좋아합니다"), "ko"),
    SentenceExercise("화장실이 어디 있나요?", "Onde fica a casa de banho?", listOf("화장실이", "어디", "있나요?"), "ko"),
    SentenceExercise("제 이름은 존입니다", "O meu nome é João", listOf("제", "이름은", "존입니다"), "ko"),
    SentenceExercise("이거 얼마예요?", "Quanto custa isto?", listOf("이거", "얼마예요?"), "ko"),
    SentenceExercise("커피 한 잔 부탁합니다", "Eu gostaria de um café", listOf("커피", "한", "잔", "부탁합니다"), "ko"),
    SentenceExercise("기차역이 어디인가요?", "Onde fica a estação de comboios?", listOf("기차역이", "어디인가요?"), "ko"),
    SentenceExercise("이해가 안 가요", "Eu não entendo", listOf("이해가", "안", "가요"), "ko"),
    SentenceExercise("지금 몇 시예요?", "Que horas são?", listOf("지금", "몇", "시예요?"), "ko"),
    SentenceExercise("계산서 부탁합니다", "A conta, por favor", listOf("계산서", "부탁합니다"), "ko"),
    SentenceExercise("예약했습니다", "Tenho uma reserva", listOf("예약했습니다"), "ko"),
    SentenceExercise("도움이 필요해요", "Preciso de ajuda", listOf("도움이", "필요해요"), "ko"),
    SentenceExercise("만나서 반갑습니다", "Prazer em conhecer-te", listOf("만나서", "반갑습니다"), "ko"),
    SentenceExercise("어떻게 지내세요?", "Como estás?", listOf("어떻게", "지내세요?"), "ko"),
    SentenceExercise("저는 아주 잘 지냅니다", "Estou muito bem", listOf("저는", "아주", "잘", "지냅니다"), "ko"),
    SentenceExercise("오늘 날씨가 좋네요", "Hoje o tempo está bom", listOf("오늘", "날씨가", "좋네요"), "ko"),
    SentenceExercise("りんごを食べるのが好きです", "Eu gosto de comer maçãs", listOf("りんごを", "食べるのが", "好きです"), "ja"),
    SentenceExercise("トイレはどこですか？", "Onde fica a casa de banho?", listOf("トイレは", "どこですか？"), "ja"),
    SentenceExercise("私の名前はジョンです", "O meu nome é João", listOf("私の名前は", "ジョンです"), "ja"),
    SentenceExercise("これはいくらですか？", "Quanto custa isto?", listOf("これは", "いくらですか？"), "ja"),
    SentenceExercise("コーヒーをお願いします", "Eu gostaria de um café", listOf("コーヒーを", "お願いします"), "ja"),
    SentenceExercise("駅はどこですか？", "Onde fica a estação de comboios?", listOf("駅は", "どこですか？"), "ja"),
    SentenceExercise("わかりません", "Eu não entendo", listOf("わかりません"), "ja"),
    SentenceExercise("今何時ですか？", "Que horas são?", listOf("今", "何時ですか？"), "ja"),
    SentenceExercise("お会計をお願いします", "A conta, por favor", listOf("お会計を", "お願いします"), "ja"),
    SentenceExercise("予約しています", "Tenho uma reserva", listOf("予約しています"), "ja"),
    SentenceExercise("助けが必要です", "Preciso de ajuda", listOf("助けが", "必要です"), "ja"),
    SentenceExercise("はじめまして", "Prazer em conhecer-te", listOf("はじめまして"), "ja"),
    SentenceExercise("お元気ですか？", "Como estás?", listOf("お元気ですか？"), "ja"),
    SentenceExercise("とても元気です", "Estou muito bem", listOf("とても", "元気です"), "ja"),
    SentenceExercise("今日は天気がいいですね", "Hoje o tempo está bom", listOf("今日は", "天気が", "いいですね"), "ja"),
    SentenceExercise("我喜欢吃苹果", "Eu gosto de comer maçãs", listOf("我", "喜欢", "吃", "苹果"), "zh"),
    SentenceExercise("洗手间在哪里？", "Onde fica a casa de banho?", listOf("洗手间", "在", "哪里？"), "zh"),
    SentenceExercise("我叫约翰", "O meu nome é João", listOf("我", "叫", "约翰"), "zh"),
    SentenceExercise("这个多少钱？", "Quanto custa isto?", listOf("这个", "多少钱？"), "zh"),
    SentenceExercise("我想要一杯咖啡", "Eu gostaria de um café", listOf("我", "想要", "一杯咖啡"), "zh"),
    SentenceExercise("火车站在哪里？", "Onde fica a estação de comboios?", listOf("火车站", "在", "哪里？"), "zh"),
    SentenceExercise("我不明白", "Eu não entendo", listOf("我", "不", "明白"), "zh"),
    SentenceExercise("现在几点？", "Que horas são?", listOf("现在", "几点？"), "zh"),
    SentenceExercise("买单，谢谢", "A conta, por favor", listOf("买单，", "谢谢"), "zh"),
    SentenceExercise("我有一个预订", "Tenho uma reserva", listOf("我", "有一个预订"), "zh"),
    SentenceExercise("我需要帮助", "Preciso de ajuda", listOf("我", "需要帮助"), "zh"),
    SentenceExercise("很高兴认识你", "Prazer em conhecer-te", listOf("很", "高兴", "认识", "你"), "zh"),
    SentenceExercise("你好吗？", "Como estás?", listOf("你", "好吗？"), "zh"),
    SentenceExercise("我很好", "Estou muito bem", listOf("我", "很好"), "zh"),
    SentenceExercise("今天天气很好", "Hoje o tempo está bom", listOf("今天", "天气", "很好"), "zh"),
    SentenceExercise("Tôi thích ăn táo", "Eu gosto de comer maçãs", listOf("Tôi", "thích", "ăn", "táo"), "vi"),
    SentenceExercise("Phòng tắm ở đâu?", "Onde fica a casa de banho?", listOf("Phòng", "tắm", "ở", "đâu?"), "vi"),
    SentenceExercise("Tên tôi là John", "O meu nome é João", listOf("Tên", "tôi", "là", "John"), "vi"),
    SentenceExercise("Cái này giá bao nhiêu?", "Quanto custa isto?", listOf("Cái", "này", "giá", "bao", "nhiêu?"), "vi"),
    SentenceExercise("Tôi muốn một ly cà phê", "Eu gostaria de um café", listOf("Tôi", "muốn", "một", "ly", "cà", "phê"), "vi"),
    SentenceExercise("Ga tàu ở đâu?", "Onde fica a estação de comboios?", listOf("Ga", "tàu", "ở", "đâu?"), "vi"),
    SentenceExercise("Tôi không hiểu", "Eu não entendo", listOf("Tôi", "không", "hiểu"), "vi"),
    SentenceExercise("Bây giờ là mấy giờ?", "Que horas são?", listOf("Bây", "giờ", "là", "mấy", "giờ?"), "vi"),
    SentenceExercise("Tính tiền, xin vui lòng", "A conta, por favor", listOf("Tính", "tiền,", "xin", "vui", "lòng"), "vi"),
    SentenceExercise("Tôi có một đặt chỗ", "Tenho uma reserva", listOf("Tôi", "có", "một", "đặt", "chỗ"), "vi"),
    SentenceExercise("Tôi cần giúp đỡ", "Preciso de ajuda", listOf("Tôi", "cần", "giúp", "đỡ"), "vi"),
    SentenceExercise("Rất vui được gặp bạn", "Prazer em conhecer-te", listOf("Rất", "vui", "được", "gặp", "bạn"), "vi"),
    SentenceExercise("Bạn khỏe không?", "Como estás?", listOf("Bạn", "khỏe", "không?"), "vi"),
    SentenceExercise("Tôi rất khỏe", "Estou muito bem", listOf("Tôi", "rất", "khỏe"), "vi"),
    SentenceExercise("Hôm nay thời tiết đẹp", "Hoje o tempo está bom", listOf("Hôm", "nay", "thời", "tiết", "đẹp"), "vi"),
    SentenceExercise("मुझे सेब खाना पसंद है", "Eu gosto de comer maçãs", listOf("मुझे", "सेब", "खाना", "पसंद", "है"), "hi"),
    SentenceExercise("बाथरूम कहाँ है?", "Onde fica a casa de banho?", listOf("बाथरूम", "कहाँ", "है?"), "hi"),
    SentenceExercise("मेरा नाम जॉन है", "O meu nome é João", listOf("मेरा", "नाम", "जॉन", "है"), "hi"),
    SentenceExercise("इसकी कीमत क्या है?", "Quanto custa isto?", listOf("इसकी", "कीमत", "क्या", "है?"), "hi"),
    SentenceExercise("मुझे एक कॉफी चाहिए", "Eu gostaria de um café", listOf("मुझे", "एक", "कॉफी", "चाहिए"), "hi"),
    SentenceExercise("ट्रेन स्टेशन कहाँ है?", "Onde fica a estação de comboios?", listOf("ट्रेन", "स्टेशन", "कहाँ", "है?"), "hi"),
    SentenceExercise("मुझे समझ नहीं आ रहा है", "Eu não entendo", listOf("मुझे", "समझ", "नहीं", "आ", "रहा", "है"), "hi"),
    SentenceExercise("समय क्या हुआ है?", "Que horas são?", listOf("समय", "क्या", "हुआ", "है?"), "hi"),
    SentenceExercise("बिल, कृपया", "A conta, por favor", listOf("बिल,", "कृपया"), "hi"),
    SentenceExercise("मेरे पास आरक्षण है", "Tenho uma reserva", listOf("मेरे", "पास", "आरक्षण", "है"), "hi"),
    SentenceExercise("मुझे मदद चाहिए", "Preciso de ajuda", listOf("मुझे", "मदद", "चाहिए"), "hi"),
    SentenceExercise("आपसे मिलकर अच्छा लगा", "Prazer em conhecer-te", listOf("आपसे", "मिलकर", "अच्छा", "लगा"), "hi"),
    SentenceExercise("आप कैसे हैं?", "Como estás?", listOf("आप", "कैसे", "हैं?"), "hi"),
    SentenceExercise("मैं बहुत अच्छा हूँ", "Estou muito bem", listOf("मैं", "बहुत", "अच्छा", "हूँ"), "hi"),
    SentenceExercise("आज मौसम अच्छा है", "Hoje o tempo está bom", listOf("आज", "मौसम", "अच्छा", "है"), "hi"),
    SentenceExercise("أحب أكل التفاح", "Eu gosto de comer maçãs", listOf("أحب", "أكل", "التفاح"), "ar"),
    SentenceExercise("أين الحمام؟", "Onde fica a casa de banho?", listOf("أين", "الحمام؟"), "ar"),
    SentenceExercise("اسمي جون", "O meu nome é João", listOf("اسمي", "جون"), "ar"),
    SentenceExercise("كم يكلف هذا؟", "Quanto custa isto?", listOf("كم", "يكلف", "هذا؟"), "ar"),
    SentenceExercise("أريد قهوة", "Eu gostaria de um café", listOf("أريد", "قهوة"), "ar"),
    SentenceExercise("أين محطة القطار؟", "Onde fica a estação de comboios?", listOf("أين", "محطة", "القطار؟"), "ar"),
    SentenceExercise("لا أفهم", "Eu não entendo", listOf("لا", "أفهم"), "ar"),
    SentenceExercise("كم الساعة؟", "Que horas são?", listOf("كم", "الساعة؟"), "ar"),
    SentenceExercise("الفاتورة من فضلك", "A conta, por favor", listOf("الفاتورة", "من", "فضلك"), "ar"),
    SentenceExercise("لدي حجز", "Tenho uma reserva", listOf("لدي", "حجز"), "ar"),
    SentenceExercise("أحتاج إلى المساعدة", "Preciso de ajuda", listOf("أحتاج", "إلى", "المساعدة"), "ar"),
    SentenceExercise("سعيد بلقائك", "Prazer em conhecer-te", listOf("سعيد", "بلقائك"), "ar"),
    SentenceExercise("كيف حالك؟", "Como estás?", listOf("كيف", "حالك؟"), "ar"),
    SentenceExercise("أنا بخير جدا", "Estou muito bem", listOf("أنا", "بخير", "جدا"), "ar"),
    SentenceExercise("الطقس جيد اليوم", "Hoje o tempo está bom", listOf("الطقس", "جيد", "اليوم"), "ar"),
    SentenceExercise("ฉันชอบกินแอปเปิ้ล", "Eu gosto de comer maçãs", listOf("ฉัน", "ชอบ", "กิน", "แอปเปิ้ล"), "th"),
    SentenceExercise("ห้องน้ำอยู่ที่ไหน?", "Onde fica a casa de banho?", listOf("ห้องน้ำ", "อยู่", "ที่ไหน?"), "th"),
    SentenceExercise("ฉันชื่อจอห์น", "O meu nome é João", listOf("ฉัน", "ชื่อ", "จอห์น"), "th"),
    SentenceExercise("อันนี้ราคาเท่าไหร่?", "Quanto custa isto?", listOf("อันนี้", "ราคา", "เท่าไหร่?"), "th"),
    SentenceExercise("ฉันขอรับกาแฟ", "Eu gostaria de um café", listOf("ฉัน", "ขอรับ", "กาแฟ"), "th"),
    SentenceExercise("สถานีรถไฟอยู่ที่ไหน?", "Onde fica a estação de comboios?", listOf("สถานีรถไฟ", "อยู่", "ที่ไหน?"), "th"),
    SentenceExercise("ฉันไม่เข้าใจ", "Eu não entendo", listOf("ฉัน", "ไม่", "เข้าใจ"), "th"),
    SentenceExercise("ตอนนี้กี่โมงแล้ว?", "Que horas são?", listOf("ตอนนี้", "กี่โมง", "แล้ว?"), "th"),
    SentenceExercise("เช็คบิลด้วยครับ", "A conta, por favor", listOf("เช็คบิล", "ด้วยครับ"), "th"),
    SentenceExercise("ฉันมีการจองไว้", "Tenho uma reserva", listOf("ฉันมี", "การจอง", "ไว้"), "th"),
    SentenceExercise("ฉันต้องการความช่วยเหลือ", "Preciso de ajuda", listOf("ฉันต้องการ", "ความช่วยเหลือ"), "th"),
    SentenceExercise("ยินดีที่ได้รู้จัก", "Prazer em conhecer-te", listOf("ยินดี", "ที่ได้", "รู้จัก"), "th"),
    SentenceExercise("คุณเป็นอย่างไรบ้าง?", "Como estás?", listOf("คุณ", "เป็น", "อย่างไรบ้าง?"), "th"),
    SentenceExercise("ฉันสบายดีมาก", "Estou muito bem", listOf("ฉัน", "สบายดี", "มาก"), "th"),
    SentenceExercise("วันนี้อากาศดี", "Hoje o tempo está bom", listOf("วันนี้", "อากาศดี"), "th")
)
